[package]
name = "tiger"
version = "0.1.0"
authors = ["Erick Hernandez Curiel <Erick.HernandezCuriel@mx.bosch.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
lazy_static = "1"
